/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesCoastalResidenceRouteImport } from './routes/properties.coastal-residence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesCoastalResidenceRoute =
  PropertiesCoastalResidenceRouteImport.update({
    id: '/properties/coastal-residence',
    path: '/properties/coastal-residence',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/properties/coastal-residence': typeof PropertiesCoastalResidenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/properties/coastal-residence': typeof PropertiesCoastalResidenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/properties/coastal-residence': typeof PropertiesCoastalResidenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/properties/coastal-residence'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/properties/coastal-residence'
  id: '__root__' | '/' | '/properties/coastal-residence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PropertiesCoastalResidenceRoute: typeof PropertiesCoastalResidenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/coastal-residence': {
      id: '/properties/coastal-residence'
      path: '/properties/coastal-residence'
      fullPath: '/properties/coastal-residence'
      preLoaderRoute: typeof PropertiesCoastalResidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PropertiesCoastalResidenceRoute: PropertiesCoastalResidenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
